### ISSUE TITLE
Контроллер пингвина 

### ISSUE THREAD

**Issue by Wolwer1nE** [mmcs-gd/pvd#2]
- [ ] Реализовать логику загрузки ассетов для пингвинов: тушки и пушки
- [ ] Реализовать логику поворота пушки по направлению стрельбы.

Что надо сдать: сцена, на которой стоят 3-4 разных пингвина (разные тушки, разные пушки). По карте перемещается 1 цель, пушки поворачиваются к цели.

**Comment by i-oktav-i** [comment]
LGTM+

**Comment by COOLIRON2311** [comment]
Resolved by #17
