### ISSUE TITLE
Статы пингвинов

### ISSUE THREAD

**Issue by Wolwer1nE** [mmcs-gd/pvd#22]
Нужно взять за основу одну из таблиц, например эту
https://docs.google.com/spreadsheets/d/1j2BwPylVYbOfkGMDcT2tFc1ayVkZArca_4NH9S6g-mc/edit?usp=sharing 

и реализовать систему, которая загружает из конфига типы пингвинов и пушек: какая картинка, какие статы.

Для проверки расположить на сцене загруженные из конфига комбинации пингвинов и пушек.

**Comment by handlessdude** [comment]
**моё**

**Comment by COOLIRON2311** [comment]
Resolved by #36
