### ISSUE TITLE
Процедурная генерация - 3

### ISSUE THREAD

**Issue by Wolwer1nE** [mmcs-gd/pvd#28]
Нужно дождаться закрытия issue https://github.com/mmcs-gd/pvd/issues/15 и взять готовую карту.
Посмотреть на нее внимательно.
И придумать, как генерить на лету все слои такой карты: землю и препятствия.
Таких issue будет 3, в каждом нужно сделать свою реализацию. Можно выбирать любые методы генерации.

**Comment by elia-morrison** [comment]
Всё ещё можно взять? Возьму.
