### ISSUE TITLE
Экран и логика загрузки

### ISSUE THREAD

**Issue by Wolwer1nE** [mmcs-gd/pvd#4]
- [ ] Добавить сцену и положить на нее спинер
- [ ] Добавить смешные надписи
- [ ] Проанализировать, нужно ли делать атласы текстур
- [ ] Обрезать края картинок (собаки, пингвины, пушки)

**Comment by Wolwer1nE** [comment]
А какой тут статус?

**Comment by COOLIRON2311** [comment]
Resoved by #34

**Comment by COOLIRON2311** [comment]
Resolved by #34
